### PR TITLE
Avoid leaking window on rotations

### LINKED ISSUE #13: Dialog disappears if device is rotated; subsequent shakes do not work
screen shot 2016-01-12 at 4 31 15 pm

### PR DESCRIPTION
**Pull request by stkent**
Closes #13 
### Goal(s)

Prevent presented dialog from leaking a reference to an activity/window that is destroyed on configuration changes.
### Testing Notes

In master: launch example app, shake, see dialog, rotate screen, see log message indicating that a window has been leaked. Try shaking again, see that dialog never reappears.

In PR: launch example app, shake, see dialog, rotate screen, do not see leak log message. Try shaking again, see that dialog reappears as expected.

### CODE REVIEW

File: bugshaker/src/main/java/com/github/stkent/bugshaker/ActivityReferenceManager.java [hunk 1]
```diff
@@ -26,14 +26,35 @@
...
-        this.wActivity = new WeakReference<>(activity);
+    @Nullable
+    private WeakReference<Activity> wPresentingActivity;
+
+    public void setTopActivity(@NonNull final Activity activity) {
+        wTopActivity = new WeakReference<>(activity);
+    }
+
+    public void setPresentingActivity(@NonNull final Activity activity) {
+        wPresentingActivity = new WeakReference<>(activity);
```
Comment (btkelly) [inline bugshaker/src/main/java/com/github/stkent/bugshaker/ActivityReferenceManager.java]: I'm not understanding the need for two here, let's chat when you're out of standup
